### ISSUE TITLE
运行代码出现 UnicodeEncodeError

### ISSUE THREAD

**Issue by cheenbee** [zzanswer/QSBK#1]
Traceback (most recent call last):
  File "QSBK.py", line 80, in <module>
    spider.start()
  File "QSBK.py", line 68, in start
    print u"正在读取糗事百科,按回车查看新段子，Q退出"
UnicodeEncodeError: 'ascii' codec can't encode characters in position 0-7: ordinal not in range(128)
[Finished in 0.962s]

**Comment by zzanswer** [comment]
python2的编码问题
加上下面三行试试
import sys
reload(sys)
sys.setdefaultencoding('utf-8')

**Comment by cheenbee** [comment]
@zzanswer 可以了 好使了 thanks
